language: nix
sudo: false
env:
  - PKG=saw-core
  - PKG=saw-core-aig
  - PKG=saw-core-sbv
  - PKG=crucible
  - PKG=crucible-saw
  - PKG=what4
  - PKG=elf-edit
  - PKG=flexdis86
  - PKG=binary-symbols
  - PKG=galois-dwarf
  - PKG=macaw-base
  - PKG=macaw-x86
script:
  - travis_wait 120 nix-build -A "haskellPackages.$PKG"
