# Generated by cabal2nix, then edited by hand
{ mkDerivation, fetchgit, aig, base, base-compat, c2hs, Cabal
, containers, directory, filemanip, filepath, QuickCheck, stdenv
, tasty, tasty-ant-xml, tasty-hunit, tasty-quickcheck, vector
# , abc
}:
let
  # For some reason, nix-prefetch-git --deepClone doesn't compute the
  # correct SHA256, so we just handle this one manually.
  src = fetchgit {
    url = "https://github.com/GaloisInc/abcBridge.git";
    deepClone = true;
    rev = "e5b6ddc63349c8b676771be672a40521f63aa8b3";
    # 1w14qm92wy9qjil5dfj9a69073jivvj02c8ybycyazwpflzwqk3l
    sha256 = "0clfbzd9zjbyyy97mxz0d0ypj987h6vw432nbsn9259zq0cb18r3";
  };
in mkDerivation {
  inherit src;
  pname = "abcBridge";
  version = "0.17.1";
  isLibrary = true;
  isExecutable = true;
  setupHaskellDepends = [ base Cabal directory filemanip filepath ];
  libraryHaskellDepends = [
    aig base base-compat containers directory vector
  ];
  # librarySystemDepends = [ abc ];
  libraryToolDepends = [ c2hs ];
  testHaskellDepends = [
    aig base base-compat directory QuickCheck tasty tasty-ant-xml
    tasty-hunit tasty-quickcheck vector
  ];
  description = "Bindings for ABC, A System for Sequential Synthesis and Verification";
  license = stdenv.lib.licenses.bsd3;
}
