#!/usr/bin/env bash

set -e

to_build=(
  abcBridge
  cryptol
  # parameterized-utils
  # saw
  saw-core
  saw-core-aig
  saw-core-sbv
  crucible
  crucible-saw
  crucible-llvm
  crucible-jvm
  what4
  cryptol-verifier
  elf-edit
  flexdis86
  binary-symbols
  galois-dwarf
  jvm-parser
  # jvm-verifier
  llvm-verifier
  llvm-pretty
  llvm-pretty-bc-parser
  macaw-base
  macaw-symbolic
  macaw-x86
  macaw-x86-symbolic
)

# Write .travis.yml
cat << EOF > .travis.yml
# This file generated by ./build-all.sh
language: nix
sudo: false
env:
EOF
for ghc in 843 822; do
  for pkg in ${to_build[*]}; do
    echo "  - GHC=ghc${ghc} PKG=${pkg}" >> .travis.yml
  done
done
cat << EOF >> .travis.yml
# https://github.com/travis-ci/travis-ci/issues/6301
# https://github.com/facebook/react/pull/2000
# https://github.com/ah-/anne-key/pull/3
before_install:
  - |
      set -e
      # fail loudly when force-pushed
      MODIFIED_FILES=\$(git diff --name-only \$TRAVIS_COMMIT_RANGE)
      # waiting for native solution https://github.com/travis-ci/travis-ci/issues/6301
      if ! echo \${MODIFIED_FILES} | grep -qvE '(\.gitignore\$)|(\.md\$)|(^docs)/'; then
        echo "Only docs were updated, stopping build process."
        exit
      fi
script:
  - travis_wait 120 nix-build --arg compiler \"\$GHC\" -A "haskellPackages.\$PKG"
matrix:
  allow_failures:
    - env: GHC=ghc822
# This file generated by ./build-all.sh
EOF

options=""
for pkg in ${to_build[*]}; do
  options="${options} -A haskellPackages.${pkg}"
done
echo nix-build $options
nix-build $options
