#!/usr/bin/env bash

set -e

# https://bit.ly/2wM4MIG
args=( "$@" )

# Write .travis.yml
cat << EOF > .travis.yml
# This file generated by 'make travis'
language: nix
sudo: false
env:
EOF
# for ghc in 843 822; do # This takes *forever*
for ghc in 843; do
  for pkg in ${args[*]}; do
    echo "  - GHC=ghc${ghc} PKG=${pkg}" >> .travis.yml
  done
done
cat << EOF >> .travis.yml
# https://github.com/travis-ci/travis-ci/issues/6301
# https://github.com/facebook/react/pull/2000
# https://github.com/ah-/anne-key/pull/3
before_install:
  - |
      set -e
      # fail loudly when force-pushed
      MODIFIED_FILES=\$(git diff --name-only \$TRAVIS_COMMIT_RANGE)
      # waiting for native solution https://github.com/travis-ci/travis-ci/issues/6301
      if ! echo \${MODIFIED_FILES} | grep -qvE '(\.gitignore\$)|(\.md\$)|(^docs)/'; then
        echo "Only docs were updated, stopping build process."
        exit
      fi
script:
  - travis_wait 120 nix-build --arg compiler \"\$GHC\" -A "haskellPackages.\$PKG"
matrix:
  allow_failures:
    - env: GHC=ghc822
# This file generated by 'make travis'
EOF
